name: Run Tests
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    env:
      CI: true
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      APP_ID: ${{ secrets.APP_ID }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

#      - name: Run Snyk to check for critical vulnerabilities
#        uses: snyk/actions/node@master
#        env:
#          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#        with:
#          args: --severity-threshold=critical

      - name: update state
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.TEST_TOKEN}}
          context: 'Test run'
          description: 'Passed'
          state: 'success'
          sha: ${{github.sha}}
      - name: slack
        uses: sonots/slack-notice-action@v3
        with:
          status: ${{ job.status }}
          text: Tests ${{ job.status }} for ${{github.actor}} on ${{github.repository}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()